-- Space Miner controller configuration.
-- Edit values here and restart the program for changes to take effect.
--
-- This whole file can also be generated by the web configurator
-- (see config-descriptor.yml). Ore targets live in ore_targets below; they are
-- overlaid by label onto the static asteroid catalog in ores.lua at startup.

return {

    -- ── Auto-update ─────────────────────────────────────────────────────────────
    -- GitHub repo ("owner/name") this program updates itself from, and the
    -- release archive name (without ".tar"). updater.lua checks the repo's
    -- main-branch version.lua on startup. PLACEHOLDER values — replace with the
    -- real repository before publishing a release.
    update_repo    = "YOUR_USER/GTNH-OC-Space-Miner",
    update_archive = "SpaceMiner",


    -- ── Timing ────────────────────────────────────────────────────────────────

    -- Seconds between full ME network scans for ore amounts.
    me_scan_interval  = 60,

    -- Seconds to sleep when all ore targets are met and no miners are busy.
    idle_sleep        = 300,

    -- ── Redstone item flow ──────────────────────────────────────────────────────
    -- Item movement between ME Interface and GT Input Bus is now handled by a
    -- pipe + redstone signal, NOT by a transposer:
    --   signal LOW  → pipe drains the Input Bus back into the ME Interface
    --   signal HIGH → items flow ME Interface → Input Bus
    -- The program simply holds the signal HIGH while a miner is working.

    -- Strength of the redstone signal emitted to enable item flow (1..15).
    redstone_on       = 15,

    -- Seconds to wait, after dropping the signal and clearing the interface,
    -- for the Input Bus to fully drain back into the ME Interface before the
    -- miner is considered idle again.
    drain_time        = 4,

    -- A drone is a reusable tool: the miner needs exactly ONE, but drones are
    -- stackable so the pipe would keep pulling more into the Input Bus. To stop
    -- that, the drone request is cleared the instant the miner activates (the
    -- one drone is already in the bus by then). These bound that handshake:

    -- Max seconds to wait for the miner to activate after the drone is loaded
    -- before giving up and returning the miner to IDLE.
    drone_load_time   = 6,

    -- Polling interval (seconds) while waiting for activation. Tight so the
    -- drone request is dropped within tens of ms of the miner starting, before
    -- extra drones can be pulled in.
    drone_poll        = 0.05,

    -- ── Drone buffer chest ──────────────────────────────────────────────────────
    -- Drones rest in a dedicated buffer chest, NOT in the ME network. A single
    -- transposer moves them between the chest and a dedicated "drone interface"
    -- wired into the network. On assignment exactly one drone is injected into
    -- the network so the pipe can never pull more than one; after a job the
    -- drone drains back into the network and vacuum() returns it to the chest.
    -- (The transposer, its chest/interface sides, and the drone interface are
    -- auto-detected by search and saved in the miners config.)

    -- Seconds to wait for AE2 to import an injected drone into the network, or
    -- to export a stocked drone into the interface buffer during recovery.
    drone_settle_time = 1.5,

    -- ── Search (auto-detection) ────────────────────────────────────────────────

    -- Seconds to wait for AE2 to stock items into an ME Interface during search.
    search_stock_time = 3,

    -- Seconds to wait for a miner to activate after items + signal are applied.
    search_start_time = 4,

    -- ── Paths ─────────────────────────────────────────────────────────────────

    -- File where auto-detected miner topology is stored.
    -- Delete this file to trigger fresh auto-detection on next launch.
    miners_config = "/home/miners.lua",

    -- ── Debug ─────────────────────────────────────────────────────────────────

    -- Print verbose messages: state transitions, scheduler scores, ME scan
    -- results. Useful for troubleshooting; disable in production.
    debug = false,

    -- ── Ore targets ─────────────────────────────────────────────────────────────
    -- Which ores to keep stocked, and how urgently. Each entry:
    --   label    : exact in-game item name (must match a label in ores.lua)
    --   target   : minimum amount to keep in the ME network (0 = ignore)
    --   priority : urgency weight; higher mines first when several are depleted
    -- At startup these are overlaid onto the static asteroid catalog in ores.lua
    -- by matching label, so only ores listed here are actively mined. This list
    -- is what the web configurator edits.
    ore_targets = {
        -- { label = "Lithium Dust",      target = 10000000, priority = 20 },
        -- { label = "Plutonium 239 Dust", target = 5000000,  priority = 100 },
    },

}
