-- Space Miner controller configuration.
-- Can also be generated by the web configurator (see config-descriptor.yml).
-- Ore targets live in ore_targets and are overlaid onto asteroids.lua at startup.

return {

    -- Auto-update: GitHub repo ("owner/name") and release archive name.
    update_repo    = "Coopper228/GTNH-OC-Space-Miner",
    update_archive = "SpaceMiner",

    -- Timing
    me_scan_interval = 60,    -- seconds between ME network scans
    idle_sleep       = 300,   -- sleep when all targets met and no miner busy

    -- Redstone item flow (signal HIGH = ME Interface -> Input Bus)
    redstone_on = 15,         -- signal strength (1..15)
    drain_time  = 4,          -- seconds to let a bus drain back before reuse

    -- Drone start handshake
    drone_load_time = 6,      -- max seconds to wait for a miner to activate
    drone_poll      = 0.05,   -- activation poll interval

    -- Drone buffer chest. Drones rest in a chest, NOT the network; a transposer
    -- moves them via a dedicated drone interface (auto-detected by search).
    drone_op_timeout = 2,     -- upper bound for inject/reclaim state polls

    -- Search (auto-detection)
    search_stock_time = 3,    -- wait for AE2 to stock an interface
    search_start_time = 4,    -- wait for a miner to activate

    miners_config = "/home/miners.lua",   -- delete to force re-detection
    debug         = false,                -- verbose logs + drone buffer diagnostics

    -- Ore targets. Each entry: label (exact in-game name, must exist in
    -- asteroids.lua), target (min amount to keep), priority (higher mines first).
    -- Only ores listed here are mined. This list is what the web configurator edits.
    ore_targets = {
        -- { label = "Lithium Dust",       target = 10000000, priority = 20  },
        -- { label = "Plutonium 239 Dust", target = 5000000,  priority = 100 },
    },

}
